### ISSUE TITLE
How to add new field in hash

### ISSUE THREAD

**Issue by ror-webExpert** [mrsool/zatca#12]
**How to add new field in hash?**

I have tried adding new fieds in tag schema by overriding the tag schema behavior by going in the lib folder and overriding the tag.rb file by freezing the added field but it gives Argument error undefined 

**My hash:**

```
tags = ZATCA::Tags.new({
  seller_name: "Mrsool",
  vat_registration_number: "310228833400003",
  timestamp: "2021-10-20T19:29:32+03:00",
  vat_total: "15",
  invoice_total: "115",
  invoice_number: '212'
})
```

error:
![Image Pasted at 2021-11-19 12-12](https://user-images.githubusercontent.com/69003744/142580676-efb045bd-cd25-4c26-97a4-366f9f539971.png)

Can you help me?

**Comment by obahareth** [comment]
Hey @ror-webExpert,

Can you explain a bit more on why you want to add invoice number to the QR Code? It's not part of the phase 1 or phase 1 implementations.

Anyways check the TagsSchema as well and override it if you need to do that but I don't recommend it as it might break, because you're adding a field ZATCA doesn't expect and isn't part of the specification.

**Comment by ror-webExpert** [comment]
Thanks for the reply
Client had asked us to add invoice number as well in QR code.
